version: "3.8"

services:
  # Example using Docker Secrets for sensitive configuration
  trakt-export-secrets:
    image: johandevl/export-trakt-4-letterboxd:latest
    container_name: trakt-export-secrets
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./copy:/app/copy
      - ./backup:/app/backup
    environment:
      - TZ=Europe/Paris
      - CRON_SCHEDULE=0 3 * * *
      - EXPORT_OPTION=normal
      # Set environment variables to read from Docker secrets
      - TRAKT_API_KEY_FILE=/run/secrets/trakt_api_key
      - TRAKT_API_SECRET_FILE=/run/secrets/trakt_api_secret
      - TRAKT_ACCESS_TOKEN_FILE=/run/secrets/trakt_access_token
      - TRAKT_REFRESH_TOKEN_FILE=/run/secrets/trakt_refresh_token
      - TRAKT_USERNAME=your_username
    secrets:
      - trakt_api_key
      - trakt_api_secret
      - trakt_access_token
      - trakt_refresh_token
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/app/docker-entrypoint.sh", "healthcheck"]
      interval: 1m
      timeout: 10s
      retries: 3

secrets:
  trakt_api_key:
    file: ./secrets/api_key.txt
  trakt_api_secret:
    file: ./secrets/api_secret.txt
  trakt_access_token:
    file: ./secrets/access_token.txt
  trakt_refresh_token:
    file: ./secrets/refresh_token.txt
