name: 📚 Documentation Issue
description: Report an issue with documentation or suggest improvements
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        # 📚 Documentation Issue

        Help us improve our documentation! Whether it's a typo, missing information, or unclear instructions, your feedback is valuable.

  - type: checkboxes
    id: confirm
    attributes:
      label: Preliminary Checks
      description: Please confirm these steps before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have checked the [Wiki](https://github.com/JohanDevl/Export_Trakt_4_Letterboxd/wiki) for existing documentation
          required: true

  - type: dropdown
    id: type
    attributes:
      label: Documentation Issue Type
      description: What type of documentation issue is this?
      options:
        - Typo or grammar error
        - Outdated information
        - Missing information
        - Unclear instructions
        - Broken links
        - Code examples not working
        - Installation/setup issues
        - Missing translation
        - New documentation needed
        - Other
    validations:
      required: true

  - type: dropdown
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue located?
      options:
        - README.md
        - Wiki pages
        - Code comments
        - Configuration examples
        - CLI help text
        - Docker documentation
        - GitHub templates
        - Release notes
        - Other/Multiple locations
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: Specific URL or File
      description: Link to the specific page or file with the issue
      placeholder: "https://github.com/JohanDevl/Export_Trakt_4_Letterboxd/wiki/page or path/to/file.md"
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Current Documentation Issue
      description: What's wrong with the current documentation? Quote the problematic text if applicable.
      placeholder: "The current documentation says... but it should say... / The section about X is missing... / Step 3 in the installation guide doesn't work because..."
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved? Provide specific suggestions.
      placeholder: "The documentation should include... / This section should be clarified by... / Add an example showing..."
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency Level
      description: How urgent is this documentation fix?
      options:
        - Critical - Blocks users from using the application
        - High - Causes significant confusion
        - Medium - Minor improvement
        - Low - Nice to have
    validations:
      required: true

  - type: checkboxes
    id: help
    attributes:
      label: Contribution Willingness
      description: Would you be willing to help fix this documentation issue?
      options:
        - label: I'm willing to submit a pull request to fix this
        - label: I can help review the corrected documentation
        - label: I can help with translation if applicable

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information, screenshots, or context
      placeholder: "Screenshots of confusing sections, links to related issues, etc."
    validations:
      required: false
